### ISSUE TITLE
Der Code

### ISSUE THREAD

**Issue by bh** [coherence-project/Coherence#12]
Der Code ist ja schon ziemlich komplex, unverständlich und unleserlich, da macht es ja kaum Spaß ein Plugin zu schreiben. 
Es gibt ja kaum Doku und vorallem keine Tests. Das ganze Projekt müsste meiner Meinung nach, neugeschrieben werden. Es müsste vorallem `zope.interface` richtig benutzt werden, so wie in Zope/Plone.

**Comment by htgoebel** [comment]
Ich arbeite darn, bzw. ich wühle mich durch. Deine Hilfe ist willkommen :-)

**Comment by htgoebel** [comment]
Maybe I've been a bit to verbose with my answer :-)

I'm currently working myself through the code, cleaning up and removing redundancies. I'm desperately missing a unit-test framework, but am unsure how one can build it given the higly async architecture. So I'd appreciate help, esp. help on a test-framework.
