### ISSUE TITLE
twisted.web.client._parse no longer available

### ISSUE THREAD

**Issue by gagern** [coherence-project/Coherence#3]
`coherence.upnp.core.utils.getPage` makes use of `twisted.web.client._parse` which is no longer available in recent versions of twisted. Namely the 13.2.0 I've installed here. The function was removed in [this merge](https://twistedmatrix.com/trac/changeset/38812/trunk/twisted/web/client.py) but [simply using the new private code](https://twistedmatrix.com/trac/browser/branches/redirectagent-final-uri-5435/twisted/web/client.py?rev=37868#L541) instead seems like a bad idea. So I suggest you either copy and paste the old `_parse` function, or use something else like [`urlparse.urlsplit`](https://docs.python.org/2/library/urlparse.html#urlparse.urlsplit).

**Comment by gagern** [comment]
I've got more problems running UPnP-Inspector against my twisted install. Next one is the fact that `coherence.upnp.core.utils.HeaderAwareHTTPClientFactory` does not call the `__init__` implementation of its super class. As a consequence, its instances lack a `_disconnectedDeferred` attribute which `HTTPPageGetter.connectionLost` relies on. Disabling the `__init__` method in coherence solved that.

**Comment by htgoebel** [comment]
If would be great if you could submit a pull-request.

**Comment by Hypfer** [comment]
Fixed.

**Comment by htgoebel** [comment]
@Hypfer: fixed where?

**Comment by Hypfer** [comment]
Fixed with https://github.com/coherence-project/Coherence/pull/6

At least the twisted.web.client._parse use.

-> Partly fixed O:)

**Comment by gagern** [comment]
There is [one occurrence of `_parse`](https://github.com/coherence-project/Coherence/blob/17e186713233a400b141b9c809322a73f62e3727/coherence/upnp/core/utils.py#L572) left, even though [one occurrence got removed](https://github.com/coherence-project/Coherence/pull/6/files#diff-113d22d672509632c8d7f39b72b3c9faL589).

**Comment by Hypfer** [comment]
Partly partly fixed.

**Comment by htgoebel** [comment]
Fixed.
