### ISSUE TITLE
How to integrate a new backend?

### ISSUE THREAD

**Issue by htgoebel** [coherence-project/Coherence#8]
Originally posted by @drunk3nm0nk3y:

Unfortunately I couldn't find any documentation about the backend system:
- I have written a simple backend, it is based on the Lolcats backend example
- My question is how to integrate my backend into Coherence? I saved my backend under:

```
/usr/lib/python2.7/site-packages/Coherence-0.6.6.2-py2.7.egg/coherence/backends/dvb_store.py
```

and I try to activate it through the config-file like this:

```
<plugin active="yes">
  <uuid>TestUID</uuid>
  <name>Dvb Store</name>
  <backend>DvbStore</backend>
</plugin>
```

My backend also contains a class called "DvbStore" (by looking at the other backends I assumed that the backend is identified by this class name), code snipped:

```
class DvbStore(BackendStore):
    implements = ['MediaServer']
    logCategory = 'dvb_store'
    ROOT_ID = 0

    def __init__(self, server, *args, **kwargs):
        BackendStore.__init__(self,server,**kwargs)
        ...
```

But when I start coherence it always says:

```
INFO  coherence:              adding plugin 'DvbStore' (coherence/base.py:429)
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
WARN  coherence:            Can't enable DvbStore plugin, not found (coherence/base.py:452)
```

I tried a lot of stuff, but I'm out of ideas. Does anyone know how to do this?

**Comment by bh** [comment]
Yeah, @drunk3nm0nk3y, you have to add an entry point to the entry_points section in setup.py

**Comment by drunk3nm0nk3y** [comment]
Hey bh, thanks a lot! I'm really surprised that there is no dynamic loading of the backends. I think this information should be added to the README.

**Comment by bh** [comment]
No problem. The entry point mechanism is cool to wrtite plugins. For example: You can create a new python package and when you register an entry point for Coherence, Coherence will load your plugin from your python project. :-)

**Comment by htgoebel** [comment]
@drunk3nm0nk3y You are welcome to submit a pull request :-)
